# Generated by Django 3.1.2 on 2022-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220403_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price2',
            field=models.IntegerField(default=1000),
        ),
    ]
