# Generated by Django 3.1.2 on 2022-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220404_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='type_name',
            field=models.TextField(choices=[(1, '新郎'), (2, '新婦'), (3, '両方')], default=3, verbose_name='宛先'),
        ),
    ]
