# Generated by Django 3.1.2 on 2022-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220404_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='type_name',
            field=models.TextField(choices=[('新郎', '新郎'), ('新婦', '新婦'), ('両方', '両方')], verbose_name='宛先'),
        ),
    ]
