# Generated by Django 3.1.2 on 2022-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220410_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
