# Generated by Django 3.1.2 on 2022-04-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220416_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='メッセージ本文'),
        ),
        migrations.AlterField(
            model_name='books',
            name='mail',
            field=models.EmailField(blank=True, default='asdf@mail.com', max_length=254, null=True, verbose_name='メールアドレス ※こちらの入力は任意です'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(verbose_name='（仮）'),
        ),
    ]
