# Generated by Django 3.1.2 on 2022-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220416_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス ※こちらの入力は任意です'),
        ),
    ]
