# Generated by Django 3.1.2 on 2022-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220416_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='type_name',
            field=models.TextField(verbose_name='宛先'),
        ),
    ]
